# Generated by Django 6.0.5 on 2026-05-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(default='🎂 Compleanni di oggi nel team {team}', max_length=200)),
                ('body_template', models.TextField(default='Ciao!\n\nOggi nel team {team} si festeggia:\n{birthdays}\n\nPassa a fare gli auguri! 🎉', help_text='Placeholder disponibili: {team}, {birthdays}')),
                ('LeapDayRule', models.CharField(choices=[('FEB_28', 'Festeggia il 28 febbraio'), ('MAR_01', 'Festeggia il 1° marzo')], default='FEB_28', help_text='Come gestire i compleanni del 29 febbraio negli anni non bisesti?', max_length=10)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('timezone', models.CharField(default='UTC', help_text="Nome IANA, es. 'Europe/Rome', 'Asia/Tokyo'", max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='employees.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reference_date', models.DateField(help_text="La data 'di calendario' per cui è stata generata la newsletter")),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('celebrants', models.JSONField(default=list, help_text='Snapshot dei festeggiati inclusi: [{name, age}, ...]')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_logs', to='employees.team')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Dipendente'), ('MANAGER', 'Manager'), ('EXECUTIVE', 'Dirigente')], default='EMPLOYEE', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="Falso = non più in azienda o sospeso (diverso da 'in ferie')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_team_name_per_location'),
        ),
    ]
