# Generated by Django 6.0.5 on 2026-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsettings',
            old_name='subject_template',
            new_name='notify_subject',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='body_template',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='birthday_body',
            field=models.TextField(default='Ciao {name},\n\ntutto il team ti augura un felicissimo compleanno per i tuoi {age} anni! 🎉\n\nGoditi la giornata!', help_text='Placeholder: {name}, {age}'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='birthday_subject',
            field=models.CharField(default='🎂 Buon compleanno, {name}!', max_length=200),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='notify_body',
            field=models.TextField(default='Ciao!\n\nOggi nel team {team} si festeggia:\n{birthdays}\n\nPassa a fare gli auguri! 🎉', help_text='Placeholder: {team}, {birthdays}'),
        ),
    ]
