# Generated by Django 6.0.5 on 2026-05-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_subject_template_emailsettings_notify_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name': 'Email settings', 'verbose_name_plural': 'Email settings'},
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='LeapDayRule',
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='leap_day_rule',
            field=models.CharField(choices=[('FEB_28', 'Festeggia il 28 febbraio'), ('MAR_01', 'Festeggia il 1 marzo')], default='FEB_28', help_text="Quando festeggia chi e' nato il 29/02 negli anni non bisestili", max_length=10),
        ),
    ]
